courses/urls.py
from django.conf.urls import url
from django.views.generic import ListView

from courses.views import CourseList
from db.course import Course

app_name = 'courses'
urlpatterns = [
    url(r'^$', CourseList.as_view(), name='index'),
]

testforyou/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url="/users/"), name='index'),
    url(r'^courses/', include('courses.urls')),
    url(r'^users/', include('users.urls')),
]

users/urls.py
from django.conf.urls import url
from users.views import CreateUserView, DeleteUserView, EditUserViewForm, UsersListView

app_name = 'users'
urlpatterns = [
    url(r'^$', UsersListView.as_view(), name='index', ),
    url(r'^create/', CreateUserView.as_view(), name='create', ),
    url(r'^delete/(?P<pk>\d+)', DeleteUserView.as_view(), name="delete", ),
    url(r'^edit/(?P<pk>\d+)', EditUserViewForm.as_view(),
        name="edit")
]

templates/base.html
{% load cache %}
{% load staticfiles %}
{% cache 500 header %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ tile|default:'Test for you' }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
    <script src="https://use.fontawesome.com/8176bbfa2c.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="{% static 'js/scrypt.js' %}"></script>
</head>
<body>
<nav>
    <div class="navbar">
        <h2 class="logo"><a href="{% url 'index' %}">Test for You</a></h2>
        <ul class="nav right">
            <li><a href="{% url 'users:index' %}">Users</a></li>
            <li><a href="{% url 'courses:index' %}">Courses</a></li>
        </ul>
    </div>
</nav>
<div class="container">
{% endcache %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>