testforyou/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url="/users/"), name='index'),
    url(r'^courses/', include('courses.urls')),
    url(r'^users/', include('users.urls')),
]

users/urls.py
from django.conf.urls import url
from users.views import CreateUserView, DeleteUserView, EditUserViewForm, UsersListView

app_name = 'users'
urlpatterns = [
    url(r'^$', UsersListView.as_view(), name='index', ),
    url(r'^create/', CreateUserView.as_view(), name='create', ),
    url(r'^delete/(?P<pk>\d+)', DeleteUserView.as_view(), name="delete", ),
    url(r'^edit/(?P<pk>\d+)', EditUserViewForm.as_view(),
        name="edit")
]

users/models.py
from django.db import models

from courses.models import Course


class CourseUser(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=100, blank=True, null=True)
    mobile_phone = models.CharField(max_length=100, blank=True, null=True)
    STATUS_CHOICE = (('inactive', 'Inactive'), ('active', 'Active'))
    status = models.CharField(max_length=8, choices=STATUS_CHOICE, default='inactive')
    created = models.DateTimeField(auto_now_add=True, editable=True, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, editable=True, blank=True, null=True)
    courses = models.ManyToManyField(Course, default=None, blank=True)

    def __str__(self):
        return self.name

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from db.course import Course


class CourseUserForm(forms.Form):
    name = forms.CharField(max_length=100, label="Name", required=True, label_suffix="")
    email = forms.EmailField(required=True,
                             label="E-mail",
                             error_messages={'required': "This field is required"},
                             label_suffix="")
    phone_pattern = r'\+\s?\d{1,2}\s?\(?\d{3}\)?\s?\d{3}\s?\d{2}\s?\d{2}'
    phone_validators = (
        RegexValidator(
            regex=phone_pattern,
            message='Please enter a valid phone number'
        ),
    )
    phone_widget = forms.TextInput(attrs={'pattern': phone_pattern})

    phone = forms.CharField(max_length=100, required=False, validators=phone_validators, widget=phone_widget,
                            label_suffix="")
    mobile_phone = forms.CharField(max_length=100, required=False, validators=phone_validators, widget=phone_widget,
                                   label_suffix="")

    STATUS_CHOICE = (('inactive', 'Inactive'), ('active', 'Active'))
    status = forms.ChoiceField(choices=STATUS_CHOICE, label_suffix="")


class CourseChoiceField(forms.ChoiceField):

    def to_python(self, value):
        return [int(item) for item in value]

    def validate(self, value):
        call = set(c.id for c in Course.all())
        c = set(value)
        if not c.issubset(call):
            raise ValidationError(
                'Invalid value: %(value)s',
                code='invalid course',
                params={'value': ', '.join([str(s) for s in value])},
            )


class CourseUserFormEdit(CourseUserForm):
    COURSES_CHOICE = [(c.id, c.name) for c in tuple(Course.all())[:5]]

    courses = CourseChoiceField(choices=COURSES_CHOICE.copy(),
                                required=False,
                                label_suffix="",
                                widget=forms.SelectMultiple(attrs={"class": "courses_select"}))

    selected = CourseChoiceField(choices=COURSES_CHOICE.copy(),
                                 label="",
                                 label_suffix="",
                                 required=False,
                                 widget=forms.SelectMultiple(attrs={"class": "invisible"}))

users/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import InvalidPage
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, DeleteView, ListView

from db.course import Course
from db.user import User
from users.forms import CourseUserForm, CourseUserFormEdit


class UsersListView(ListView):
    template_name = 'users/index.html'
    context_object_name = 'course_users'

    def get_queryset(self):
        username = self.request.POST.get('user')
        if username:
            return tuple(User.filter(name=username))
        return tuple(User.all())

    def get_paginate_by(self, queryset):
        paginate_by = self.request.GET.get('paginate_by')
        if not paginate_by:
            paginate_by = 5
        return paginate_by

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['per_page'] = (3, 5, 10)
        return context

    def paginate_queryset(self, queryset, page_size):
        paginator = self.get_paginator(
            queryset, page_size, orphans=self.get_paginate_orphans(),
            allow_empty_first_page=self.get_allow_empty())
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        try:
            page_number = int(page)
        except ValueError:
            if page == 'last':
                page_number = paginator.num_pages
            else:
                raise Http404("Page is not 'last', nor can it be converted to an int.")
        page_number = paginator.num_pages if page_number > paginator.num_pages else page_number
        try:
            page = paginator.page(page_number)
            return (paginator, page, page.object_list, page.has_other_pages())
        except InvalidPage as e:
            raise Http404('Invalid page (%(page_number)s): %(message)s' % {
                'page_number': page_number,
                'message': e,
            })

    def post(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class CreateUserView(FormView):
    template_name = 'users/create.html'
    form_class = CourseUserForm
    success_url = reverse_lazy('user:index')

    def form_valid(self, form, **kwargs):
        user = User()
        user.name = form.cleaned_data['name']
        user.email = form.cleaned_data['email']
        user.phone = form.cleaned_data['phone']
        user.mobile_phone = form.cleaned_data['mobile_phone']
        user.status = form.cleaned_data['status']
        user.save()

        context = self.get_context_data(**kwargs)
        messages.add_message(self.request, messages.INFO, 'User created successfully')

        return render(self.request, self.get_template_names(), context=context)

    def form_invalid(self, form):
        print('invalid')
        return super().form_invalid(form)


class DeleteUserView(DeleteView):
    pk_url_kwarg = "pk"
    success_url = reverse_lazy('users:index')

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        if pk:
            obj = User.get(id=pk)
            if obj:
                obj.delete()
        return redirect(self.success_url)


class EditUserViewForm(FormView):
    template_name = "users/edit.html"
    success_url = reverse_lazy('users:index')
    form_class = CourseUserFormEdit

    def get_initial(self):
        initial = super().get_initial()

        user = self.get_user()
        initial['name'] = user.name.split()[-1]
        initial['email'] = user.email
        initial['phone'] = user.phone
        initial['mobile_phone'] = user.mobile_phone
        initial['status'] = user.status
        selected_courses_id = [c.id for c in user.courses]
        initial['courses'] = selected_courses_id
        initial['selected'] = selected_courses_id
        return initial

    def get_user(self):
        try:
            _id = int(self.kwargs.get('pk'))
        except:
            raise Http404
        return User.get(id=_id)

    def form_valid(self, form):
        user = self.get_user()
        user.name = form.cleaned_data['name']
        user.email = form.cleaned_data['email']
        user.phone = form.cleaned_data['phone']
        user.mobile_phone = form.cleaned_data['mobile_phone']
        user.status = form.cleaned_data['status']
        courses = form.cleaned_data['selected']
        user.courses = [Course.get(id=_id) for _id in courses]
        user.update()

        context = self.get_context_data()
        messages.add_message(self.request, messages.INFO, 'User updated successfully')

        return render(self.request, self.get_template_names(), context=context)

templates/users/create.html
{% extends 'base.html' %}
{% block content %}
    {% if messages %}
        <div class="msg">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
        <script>setTimeout(function () {
            window.location = '{% url 'users:index'%}';
        }, 3000)</script>
    {% endif %}
    <a href="{% url "users:index" %}" class="btn-back"><i class="fa fa-angle-left"></i></a>

    <h1>Create user</h1>

    <form class="user" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

templates/users/edit.html
{% extends 'base.html' %}
{% block content %}

    <a href="{% url "users:index" %}" class="btn-back"><i class="fa fa-angle-left"></i></a>

    <h1>Change user</h1>

    <form class="user update" method="post">
        {% csrf_token %}
        {{ form }}
        <div class="btn-add-course" href>+</div>
        <div id="selected"></div>
        <div class="clear"></div>
        <button type="submit" class="save-user">Save</button>
    </form>

    {% if messages %}
        <div class="msg">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
        <script>setTimeout(function () {
            window.location = '{% url 'users:index'%}';
        }, 3000);
        $("select[name=courses]").remove();
        </script>
    {% endif %}
{% endblock %}

templates/users/index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url "users:create" %}" class="btn-add">+</a>
    <form class="search" method="post" action="{% url "users:index" %}?paginate_by={{ paginator.per_page }}">
        {% csrf_token %}
        <button class="btn-search" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
        <input placeholder="Username" value="{{ request.POST.user }}" type="search" name="user" list="users"/>
        <datalist id="users">
            {% for u in course_users %}
                <option>{{ u.name }}</option>
            {% endfor %}
        </datalist>
    </form>
    <select class="how-many">
        {% for i in per_page %}
            {% if i == paginator.per_page %}
                <option selected>{{ i }}</option>
            {% else %}
                <option>{{ i }}</option>
            {% endif %}
        {% endfor %}

    </select>
    <h1>Users</h1>
    <table>
        <colgroup>
            <col/>
            <col/>
            <col/>
            <col/>
        </colgroup>
        <thead>
        <tr>
            <th>Name</th>
            <th>E-mail</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for u in course_users %}
            <tr>
                <td>{{ u.name }}</td>
                <td>{{ u.email }}</td>
                <td>
                    <span class="{{ u.status|lower }}">{{ u.status|capfirst }}</span>
                </td>
                <td>
                    <a href="{% url "users:edit" u.id %}" class="edit"><i class="fa fa-pencil"
                                                                          aria-hidden="true"></i></a>
                    <a href="{% url "users:delete" u.id %}" class="delete"><i class="fa fa-trash"
                                                                              aria-hidden="true"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div>
        {% if is_paginated %}
            <ul class="paginator">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}&paginate_by={{ paginator.per_page }}" class="prev"><i
                            class="fa fa-angle-left fa-2x"></i></a></li>
                {% else %}
                    <li><a class="done"><i class="fa fa-angle-left fa-2x"></i></a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li><a href="" class="current">{{ i }}</a></li>
                    {% else %}
                        <li><a href="?page={{ i }}&paginate_by={{ paginator.per_page }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}&paginate_by={{ paginator.per_page }}" class="next"><i
                            class="fa fa-angle-right fa-2x"></i></a></li>
                {% else %}
                    <li><a class="done"><i class="fa fa-angle-right fa-2x"></i></a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
{% endblock %}